CREATE TABLE books(
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author_name VARCHAR(255) NOT NULL,
    publisher_name VARCHAR(255) NOT NULL,
    demo Text NOT NULL)